nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
            max_age: 3600
        '^/contact': 
            allow_origin: ['*'] 
            allow_headers: ['*']
            allow_methods: ['POST', 'OPTIONS']
            max_age: 3600
